language: node_js
node_js:
- 10
before_script:
- npm install -g gulp-cli gulp@4
script:
- gulp
- npm run coverage
branches:
  only:
  - master
  - develop
cache:
  directories:
  - node_modules
env:
  global:
    secure: pr48t4ePy872ZD8k65pa1b1ybLtvvvc+ItjwrKSqgk4MrO02khtwIv7ZwP5OKsct8MTOsOrpyhzJYxvTsF593W37bXSCsipHo20Vpx032PTrGGO36iwkCOEX2jpglW1fyTrv/Qhwl9aDAaZGxKoNBUZQtd39JfFGrAggGMs8ELgoJKflRPVofx3bNWzDuheA8Jv4gMascSUW2otTkgh60f1ijKuD+K8hSjVNBdPUty3nH05u4RV++XgeFudy610q6wxEIuBdyOWlLnOqJQIdG/UaDqtKLUYxD/63dDA4grSNTNPwKXoQjwDlNz0CbRp06jq/2auEn+pkljIpnXQgN5DmiTRa08IPqDlRe1rvIGxlvrrP1SO7/feFz8XaDfzDs2MNYn9268+exe98Mf4KRy0bkq5JLF/qobRM8RqpKntJUTzncZrWLDTU6gPWck6KL08ko4Oa8i/hzW6Hryyaf99W46U6gY6Qx1F2Nrzc0EwBN2AB0PH8+ia6K51GcPFTZOCDmLVt89IXY/OpIN9RcrydMo9/X4RFxpjd7cJEBjmWzkqa3gAyk0RF3by9tycQU0g0rFN5MlBflT5onnbNcIawoPBLHott1IDy/ZnavEECpaIi202KiFM0y6J/FiNZyDo/gmNp8XzEKLswkZ25730KhPpNSYxnzrMK4UrLcz4=
notifications:
  slack:
    secure: eyDquCWNqokzCwJ6OPfr4KP9s5lDgQ6V5X9gQbb/2Hk1RJ5rmnWsbuRQlXHOjmb1Jm8QQydnqzAez/NI+rs+XR43t17J/ppEYaQJVHsC/Kym8TZ5qVcGua51keUBBlFdeVJNAcqCBYiOiYL/8+9esdzFST8F5do+gwHYevM5d9jrAcgfjag+TbuF7eE/tLzJJ+ktlZ3jXnzJZY54GaEcNoGSK8QK0K6YvvwTrQ4W51zP2uhpwrnnPrgRKDXMa5vLntE8ZeToHC30H6YnZiIw52L5oYLLb7VHK2No81VIWwcpf7CcUoMCGDXWAV+OvfhV1aEqy4dvY4a8Kc6u6/VFB9eH2pS2TGAphD3MNjrBYC3X9x7CLvUYHq+uS09PWuvFeloAuKfUZFvvyYjAxs9zY0Xl7DPGL2s8MWRk+fPi9Ewc/9Ia7+pLoB5MO4wWpu2tjOEmhj+FMh91LGQ599yIFH8jsOp1l4guYLOa0Q+5N6FxVg3XvH/T1cgC5YvwZWqndgEhrZVPx5J/svCAPVGnnQguPdIXIGcp0VXYYMkd/Z7dtxI/v9I/zDjkI8ag5oxJyFOZHhbnU/GUs9TOY2SLzlQJMMs8LW3/bQNU/+bOqwBhOJUXret6os92x/wesASH6NLvffUrfc8pbyA2g18kklGWW/ng2/Lz+z/HgjbCONI=
deploy:
- provider: npm
  on:
    branch: master
  api_key:
    secure: YdKJ/rKLRwtExSXtF7Ny20szEnY4OlWjkvIyJhLHwZCK37bmRH6UDn6SymcMC13cuz9OErIVxdCrm6czPwDa9mFiSLDa5DAi8d4E7DAHweTjKxrZC3DKoB2bHkXQ+TKaC6qSMu8/1usKzRi1rcpdsLPHjXlIJKd8sMoY6dDnqkzV5UB5pcVaENjHDTGbGWvd3vbz5X595BZoXAkS/S6fSBx0W3mWTbhaHC50JcanlAcE+MXp0Z1z7L0di8caDyBLpdLhRXthD7uawqLqcU0XHnlmZr4UQk1TFFPQ98BRxRgdMQhI29sKM9Ys3XVJdYdAKH/LfV/ffIpTCG8JM2bFLMBXZuNNXtT/kizpJzb1lq+FnPudlLor9Meht2q3p2CR3NVvDGc1CjaF9CofVNJfz/93nTPfNbwTkK8R7dbnFMFYHiN07vejTx8azn3tYG5oTCHHL+6C6OZnfqNO7w9QifueH7xHBSUz7/+4h7SGF+kgqreScGLVXy8fC8hkhtJuOvgKuvIx1eNSqEqVOoU+RhWq5klXLsCRtyidaezNMzOB8Qt4DHXQDB/N+axTwgZfkNSZSsTRDKPyUyw5ZWUXQT+KGfADccISeAnyApAYSOnylXXThADwybMW/8/EWGIg62Vhbtb+NkdpSQjBm5dCOxvp4ODfWaf79SNW2GedwCY=
  email:
    secure: X+d24R5uX+2jzEsg8yZ4Mk8F4bueJWgkRtV99Lz9uzg5nGWSDkD655cIZrCFBhOVlNcLM2khsWNQcNdaP5GbA8Csg1VsU+5Gi1NabxSvKv9JbLGVjxwpRNpAKTQzmWGwE7sv2R1kgjYuqCDTzrlEnY3ndR/t4a0ID4dk7es4xHSndbG0gwglxmOPL07k7YGKMc5W+oWrkiMmTqG2vZ1FHurJruj378NDmMAtdi2MqTo26jiJz4SYsCsNAICsLCq+6e51hcbdK3UnQBOrqDrVUgshbIPaI7r1uuKb3fdC2HAN4MunLAj/va5A7239P2v6St1/tbXGIn007pG86oBH4WyZ+WB1QooZggGrI8HJCeld6odseac0B+iA9/tgtUz/hqeumymq5TJsU6an5shC/9MVudj1hxkZdn7lIi8+VBsKN9tFKopdIhpku/5mUWYKjyXJwtjmbUiP4jFIxQGi4Yjm5WfymM32c8gWGx9a/k5CqHfAyt+ebViZdtlAzGCpUrFBEI40NRG9D1NXEyw0OWpm+0MdhNveIkAKxQ8fAih+WaIgCM/PLRm2P1JecDfOl1P7l5p+vRs9wy7uAac7glkX1j2scG74tqWh7CiDkbTZc9U4JzjaO1mjk+9crYPCGY/os0AjtrS3gdHWRvrbjlzrMW2jPulsEdUsgfkaPlw=
