language: node_js
node_js:
- node
before_script:
- npm install -g gulp-cli
- npm install -g license-cli
script:
- gulp
- npm run coverage
- license-cli auth $FOSSA_API_TOKEN
- license-cli scan -r $TRAVIS_COMMIT || true
cache:
  directories:
  - node_modules
env:
  global:
  - secure: qz+adZh+VJPpKpRSe8pr2dtfwfgbXPfA30jrBa9CW9aSm5aMjKU5zqU+u34G1Jk/A1euOuqZ7t6ORUW65KqTHZxvu5fboHpaVDfjR6usYgDjeYt0hR19sP/jCrR4uNyZbqOs8Pdg4FR7Yke7WsKkmFKh9Z561c6QcU5gIUIR3/9uRor/zyjp00h5aEv5YSFGWbd1CsddG5RL0tVw1XfMEAbuMFpa6BbmG45FSFI6k3BVa2X2tUUmi6VZieG6UaAz55YBn+nRv4LLXXR2EO3TZSn5Tid5UhaU955t2UKwdcRzeIo0oSZNM14tsOAxuDk51Nz7WucT2wVwV8qEXe9lhraTF2f4a2gx6KQSCSwi8dF6wPxDM7kJ5HiAUc4EDBRrGDKvcaNj2fCEZyM2AKJPXCoUysZyOxF5K5cjoTbMkwtDm7bR9M1yd5MTQ51jt3604JLvkSMjOjCZvEDWxFCSxAE4ktedCcU7JzxCHuklemJdnfZb1RGNUz796aNB8zRC1JCWcpwSO328xAXpYu4h3GMVqpZUI1Fg7xOZHZPVTZpT1mJJzI3z9HinGW8pwWsFHbuyawd0JiI7PteYFwEKYOKy+jeztOHaDHS+gBL0tyGNUia1C0QKEVNyKLMynGYMTwvqWxpnT0FTR9JSV+TPp0bVPngpEbh0O+rJxBa27n4=
  - secure: F8buJtanB5DpkUqzP8rOK3Y9q5auPON795wkxZih1RyHSwT9cVOjpWcL1owWWXWVzY8hTya1jW7V1hKxP96ijefZSVExUrS5bktB+MW7F1icVw3hIc5KPU30Ryer6S2I7PxzyANbE3rzle+KUsJLS02X8TOAzwmfXw8fevrrOLCI64tIgIj1gQg42O+OP9KJ1MvkiNaYGasvKFR/SjBOGNN45kjT+pjssOmQRj8zRcoxr5kDR7cr9nf/PzPtNWp2W5o6voskXpylVSLyU991OEj/RlXV4geDx/u3OfEyLtkrgbJqVHj1YqsGfFpj/GZIRuEV/uWiARKpHfxkDolWTnHAMdtZbuYUPz1F4kBWbTKyx0Wz4wQr3yQZDlZoTVu2apeCI7X5+IaUZmMINvstWRaEKQr5K6xbqnut/oalJNbw7ksTDZvyomBmZPRK+kPq+As0l3yHi8XJQ/u6R6vyDjCzAF+SmQXQ8LrUYXj4VBq0RXk92y+kmvyu89nC/xipnxjfZDBI3VBWssdgTEgB5h+JbpouB+bRQ/hxcL/qfd6XY+30GmQyIQZuHQYlsZ+XcWmXSeqx3i1f2rX8rzLMaIgK6GD4FCqd0X9bRCrVffn7rM+HggfWAhHi6/0/fBrgddxz61cNyijZyIA+EiIMKwKKkMb6MqtS65YQbAK1RSg=
